feed/urls.py
from django.urls import path

from . import views

app_name = 'feed'

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post")
]

til/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace="feed")),
    url("", include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.text[0:100]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    image = ImageField(upload_to="profiles")

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created."""
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post

class HomePage(ListView):
    http_method_names = ['get']
    template_name = 'feed/homepage.html'
    model = Post
    context_object_name = 'posts'
    queryset = Post.objects.all().order_by('-id')[0:30]

class PostDetailView(DetailView):
    http_method_names = ['get']
    template_name = 'feed/detail.html'
    model = Post
    context_object_name = 'post'

class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "feed/create.html"
    fields = ['text']
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

profiles/views.py
from django.shortcuts import render

# Create your views here.

feed/templates/feed/create.html
{% extends 'base.html' %}

{% block title %}Create a new Post{% endblock %}

{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col">
        <form method="post" action="."> {% csrf_token %}
          <div class="form-outline mb-4">
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block mt-4">Create Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

feed/templates/feed/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ post.text|capfirst }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col card">
        <div class="card-header text-center">
          <h3 class="card-title">{{ post.text|capfirst }}</h3>
        </div>
        <div class="card-body">
          <p class="card-text">{{ post.text }}</p>
        </div>
        <div class="card-footer text-muted">
          <div class="row">
            <div class="col" style="padding-top: 5px;">
              Posted on {{ post.date|date:"F j, Y, g:i:a" }}
            </div>
            <div class="col" style="padding-left: 30rem; padding-top: 7px">
              {% thumbnail post.author.profile.image "40x40" crop="center" as img %}
                <img src="{{ img.url }}" class="img-fluid rounded">
              {% endthumbnail %}
              <a href="#" class="ml-2">{{ post.author.username|capfirst }}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

feed/templates/feed/homepage.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %}HomePage{% endblock %}

{% block content %}

<div class="container">

  <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-10">

        <!-- Blog Post -->
        {% for post in posts %}
          <div class="card mb-4" style="width: 50rem;">
            <div class="card-body">
              <h2 class="card-title">Post Title</h2>
              <p class="card-text">{{ post.text }}</p>
              <a href="{% url "feed:detail" post.id %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              <div class="row">
                <div class="col" style="padding-top: 5px;">
                  Posted on {{ post.date|date:"F j, Y, g:i:a" }}
                </div>
                <div class="col" style="padding-left: 30rem; padding-top: 7px">
                  {% thumbnail post.author.profile.image "40x40" crop="center" as img %}
                    <img src="{{ img.url }}" class="img-fluid rounded">
                  {% endthumbnail %}
                  <a href="#" class="ml-2">{{ post.author.username|capfirst }}</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

  </div>
</div>

<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

til/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="{% url 'feed:index' %}">Home</a>
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        {% if request.user.is_authenticated %}
          <span class="navbar-text text-light">Logged in as: {{ user.username|capfirst }}</span>
        {% endif %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:new_post' %}">Create Post</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  {% block content %}
  {% endblock %}

  {% if request.user.is_authenticated %}
    <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum maiores, repellendus sed illo vel corporis, libero ullam quasi corrupti mollitia magnam, possimus iure reprehenderit deleniti, at porro doloremque suscipit! Excepturi!</div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              Close
            </button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

  <script type="text/javascript">
    $(window).on('load', function() {
        $('#exampleModal').modal('show');
    });
  </script>
</body>
</html>